apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-pipeline-run-
spec:
  pipelineRef:
    name: tekton-pipeline
  params:
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: https://github.com/dimitristelmakh/express-sample-app.git
    - name: image-repo
      value: quay.io/dimitri_stelmakh/express-sample-app
  serviceAccountName: build-bot
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
