apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: dimitri_stelmakh-express-sample-app
  app.kubernetes.io/instance: dimitri_stelmakh-express-sample-app-express-sample-app-instance
  app.kubernetes.io/name: dimitri_stelmakh-express-sample-app
